[workspace]
members = ["fs", "io", "process", "date"]
resolver = "2"

[workspace.dependencies]
adana-script-core = "0.14.2"
anyhow = "1.0.75"
chrono = "0.4.31"

[workspace.package]
version = "0.0.3"
authors = ["Nordine Bittich"]
description = "Adana standard library"
documentation = "https://github.com/nbittich/adana-std"
rust-version = "1.72.1"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 'z'   # Optimize for size.
lto = true        # Link Time Optimization (LTO)
codegen-units = 1 # Set this to 1 to allow for maximum size reduction optimizations:
panic = 'abort'   # removes the need for this extra unwinding code.
strip = "symbols"
