[package]
name = "adana-std-date"
version = { workspace = true }
edition = { workspace = true }


[lib]
crate-type = ["dylib"]

[dependencies]
adana-script-core = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["rustc-serialize"] }
